"""Build a self-contained research report with an interactive pixel comparator."""
from pathlib import Path
import json, base64, html

ROOT=Path(__file__).resolve().parent
data=json.loads((ROOT/'viewer-data.json').read_text())
data['masks']=[dict(id=x['id'],variant=x['variant'],method=x['method'],ink=''.join(map(str,x['ink']))) for x in data['masks']]
summary=json.loads((ROOT/'summary.json').read_text())
audit=json.loads((ROOT/'source-audit.json').read_text())
ablation=json.loads((ROOT/'ablation.json').read_text())
verify=json.loads((ROOT/'verification.json').read_text())

def picture(name,caption):
 b64=base64.b64encode((ROOT/name).read_bytes()).decode()
 return f'<figure><img src="data:image/png;base64,{b64}" alt="{html.escape(caption)}"><figcaption>{caption}</figcaption></figure>'

names={'solid_50':'Solid, fixed 50%','solid_auto':'Solid, per-item Otsu','stencil_auto':'Stencil Auto','stencil_60':'Stencil Cuts 60','stencil_100':'Stencil Cuts 100, no edges','stencil_100_edges100':'Stencil Cuts 100 + Edges 100%','stencil_trim':'Stencil Auto + Trim','normalized50':'Per-item range midpoint','lab_otsu':'Lab lightness + Otsu','linear50':'Linear luminance, fixed 50%','linear_otsu':'Linear luminance + Otsu','bilateral_otsu':'3×3 bilateral + Otsu','local_mean':'Masked local mean, 5×5','sauvola':'Masked Sauvola, 5×5','pca_otsu':'RGB PCA projection + Otsu','budget20':'Interior percentile + singleton cleanup','stencil_clean':'Stencil Auto + singleton cleanup','edges_clean':'Stencil strong edges + singleton cleanup','c2g10_45_solid_auto':'Color2Gray α10 θ45 + Solid Auto','c2g10_45_stencil_auto':'Color2Gray α10 θ45 + Stencil Auto','c2g25_45_solid_auto':'Color2Gray α25 θ45 + Solid Auto','c2g25_45_stencil_auto':'Color2Gray α25 θ45 + Stencil Auto'}
metrics_rows=''.join(f'<tr><td>{names.get(m,m)}</td><td>{v["mean_retained"]:.1%}</td><td>{v["empty_items"]}/65</td><td>{v["items_with_extra_fragments"]}/65</td><td>{v["single_ink"]}</td><td>{v["single_cuts"]}</td></tr>' for m,v in summary.items())
audit_rows=''.join(f'<tr><td>{x["group"]}</td><td>{x["width"]} × {x["height"]}</td><td>{x["colors"]}</td><td>{x["opaque"]}</td><td>0, 255 only</td></tr>' for x in audit)
abl_rows=''.join(f'<tr><td>{names[x["method"]]}</td><td>{x["variant"]}</td><td>{x["changed_items"]}/65</td><td>{x["changed_pixels"]}</td></tr>' for x in ablation if x['variant'] in ['gray','palette4','palette8','palette16'])

body='''
<header><p class="eyebrow">Bitify · research on the supplied sprites · October 8, 2026 · HEAD b2711a4</p>
<h1>One ink needs a decision about shape.</h1>
<p class="lead">A universal grayscale threshold cannot reliably turn shaded 16 × 16 inventory art into a consistent minimal icon family. The strongest next step is per-item structural simplification with bounded, coherent cuts and a choice of a few candidates. Color reduction alone does not solve it.</p>
<p>Study: the breastplate plus 64 inventory cells from the four original PNGs. Baselines use the actual app code. Experimental algorithms run offline. No production behavior was changed.</p></header>

<section><h2>Compare any of the 65 items</h2><p>Every output is one opaque ink plus transparency. The small samples are exactly 16 × 16 CSS pixels; enlarged samples use nearest-neighbor pixels. Cell IDs are sheet-row-column. Compare on both light and dark backgrounds.</p>
<div class="controls"><label>Item<select id="item"></select></label><label>Input preparation<select id="variant"></select></label><label>Candidate A<select id="methodA"></select></label><label>Candidate B<select id="methodB"></select></label><label>Background<select id="background"><option value="checker">Checker</option><option value="dark">Dark</option><option value="light">Light</option></select></label></div>
<div id="samples"></div><p id="sampleStats"></p>
<details><summary>Explore every breastplate threshold</summary><p>Solid’s slider is an absolute brightness threshold. Stencil’s slider is an offset above its darkest outline pixel. For this breastplate that outline level is zero. At Cuts 76, the brightness-cut guard switches off.</p><label>Threshold / Cuts <input id="sweep" type="range" min="1" max="254" value="60"><output id="sweepValue">60</output></label><div id="sweepSamples"></div></details></section>

<section><h2>What the breastplate demonstrates</h2>
<p>The original contains <strong>155 opaque pixels and 52 unique foreground RGB colors</strong>. Its rounded outer footprint includes a dark outline, brown straps and a shaded metal body. Those colors and brightness gradients help us read its parts. A filled outline or a luminance split loses different parts of that information.</p>
<p><strong>The proposed 50% clamp is already Solid with Brightness Luma, threshold 127, first color None.</strong> On this image it keeps 24 pixels (15.5% of the opaque source), in four eight-connected fragments, including two single pixels. Solid Auto picks 69 and keeps 62 pixels in three fragments. Neither is a convincing universal repair.</p>
<p>Stencil Auto keeps 116 pixels and a continuous silhouette, but its large asymmetric cut follows the dark shading as well as the straps. My visual assessment: it can resemble a round shield or plate more than a breastplate. More retained pixels does not mean better recognition.</p>
<p><strong>Cuts is discontinuous.</strong> Its source-outline level is 0, its Otsu cut is 69, and its four-neighbor interior median is 76. With Edges off, Cuts 75 keeps 114 pixels; Cuts 76 keeps all 155. The condition <code>body &gt; dark</code> suppresses every brightness cut together. A darker body is evidence of darkness, not proof that it has no meaningful internal structure.</p>
<p>The four-neighbor outer rim has 41 pixels. Keep preserves those and pixels near transparent diagonal neighbors. Trim removes the entire rim, including useful colored edge pixels, and fragments the breastplate. An eventual trim policy needs to distinguish a drawn dark outline from the object’s actual boundary.</p>
BREAST_BASE
BREAST_ALT
<p>The local methods recover a connected body here, but add conspicuous holes; bilateral filtering barely changes the problematic split. The percentile prototype is tidier but still looks like a generic filled plate. None of these experiments warrants claiming the breastplate is solved.</p></section>

<section><h2>Grayscale and a limited palette: controlled tests</h2>
<p>Bitify already computes rounded <code>0.2126 R + 0.7152 G + 0.0722 B</code> for thresholding. Replacing RGB with exactly that gray value produces <strong>zero changed pixels on all 65 items</strong> for Solid Auto, Solid 50% and Stencil Auto with Edges off. Preconverting to the same grayscale is redundant.</p>
<p>There is an exception: edges use the largest difference in any RGB channel. Grayscale preprocessing changes the strong-edge Stencil result on 39 items, by 236 pixels in total. It suppresses some chromatic texture and may also erase useful boundaries between differently colored parts. Brightness Value or R/G/B changes the tone decisions but retains the original RGB edge measurements. These controls are not interchangeable with converting the input to grayscale.</p>
<p>The images have binary alpha already: no partly transparent pixels. Individual cells contain 16–56 foreground colors; whole sheets contain 211–242. The breastplate is comparatively color-rich, but color count is not itself a semantic defect. The source problems are mostly how shading, materials, texture and outlines are encoded.</p>
AUDIT_TABLE
<p>I quantized foreground RGB to 4, 8 and 16 colors using median cut, without dithering and without letting transparent RGB consume palette slots. I tested both a palette for each 16 × 16 cell and a shared palette for each sheet. Stencil Auto changed on 25, 27 and 21 items respectively with per-cell palettes; there was no consistent visual benefit. Quantization sometimes adds detail to a potion and sometimes removes a strap or changes an already useful hole. A four-color image can still have the wrong arrangement of shades.</p>
ABL_TABLE
PALETTE_IMG
<p>These are changes from the original mask, not quality scores. Designing an image from the start with explicit outline, material, highlight and detail roles is a different intervention from quantizing an already shaded image.</p>
<p>Runtime also does not justify a preprocessing requirement: seven repeated warm Node batches gave about ORIGINAL_MS ms per 65 original items and GRAY_MS ms per 65 gray items for analyze + first Stencil mask. This small desktop difference excludes grayscale preparation, decoding and rendering. It is not a phone benchmark; both paths still inspect RGBA pixels and compute analysis. Exported indexed PNG size is a separate concern.</p></section>

<section><h2>Which algorithms fit this goal?</h2>
<p>The key distinction is <strong>binary tone reproduction versus icon design</strong>. A threshold reproduces bright regions. A minimal icon needs the identifying shape and a few meaningful gaps. Design systems emphasize consistent weight, clear silhouettes, spacing and simplified, front-facing forms; they do not define a universal 50% image-conversion rule. The numerical grid/stroke rules of vector UI systems should not be transplanted literally to 16px pixel art. <a href="https://www.ibm.com/design/language/iconography/ui-icons/design/">IBM design guidance</a>; <a href="https://m1.material.io/style/icons.html">Material icon guidance</a>.</p>
<table><thead><tr><th>Family</th><th>Result on these inputs</th><th>Implication</th></tr></thead><tbody>
<tr><td>Fixed threshold; normalized midpoint</td><td>Fixed 50% empties 6/65 items. Range normalization avoids emptiness here but often leaves fragments.</td><td>A baseline or manual control, not a universal Auto.</td></tr>
<tr><td>Per-item Otsu</td><td>Avoids empty outputs but adds fragments in 43/65 cells.</td><td>Its statistical objective is separation of tone classes, not recognition. See the <a href="https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_thresholding.html">official thresholding guide</a>.</td></tr>
<tr><td>Value, individual channels, Lab lightness</td><td>Change which materials survive. No consistent breastplate repair.</td><td>Useful candidate diversity. A saturated red may be dark in Luma yet bright in Value.</td></tr>
<tr><td>Linear-light luminance</td><td>Fixed 50% empties 18/65; linear Otsu still fragments many items.</td><td>Physical luminance and perceptual design goals differ. The app’s weighted encoded RGB is a luma-like heuristic; true sRGB relative luminance first linearizes channels, as specified by <a href="https://www.w3.org/TR/WCAG22/#dfn-relative-luminance">W3C</a>. That does not make it the best icon mask.</td></tr>
<tr><td>Local mean / Sauvola</td><td>Improve the breastplate’s body continuity, but preserve armor texture and create many small details.</td><td>Investigated with alpha-aware 5×5 windows. Sauvola targets uneven-background binarization, especially text, not object understanding. <a href="https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_niblack_sauvola.html">Official explanation</a>.</td></tr>
<tr><td>Edge-aware smoothing</td><td>A masked 3×3 bilateral filter changes little on the breastplate.</td><td>Useful for high-frequency color noise. Strong patterned texture and shading remain. This one parameter setting is not a rejection of every bilateral/guided filter. <a href="https://research.adobe.com/publication/bilateral-filtering-theory-and-applications/">Bilateral-filter reference</a>.</td></tr>
<tr><td>Color2Gray / contrast-preserving decolorization</td><td>Actual Color2Gray experiments change some materials, but leave the breastplate ambiguity and can introduce texture cuts.</td><td>Preserving chromatic contrast is valuable when equal-lightness colors carry structure. It still does not decide which structure is important. <a href="https://www.cs.northwestern.edu/~ago820/color2gray/color2gray.pdf">Gooch et al., 2005</a>; <a href="https://www.cse.cuhk.edu.hk/~leojia/papers/siga12t_color2gray.pdf">Lu et al., 2012</a>.</td></tr>
<tr><td>Dithering / diffusion</td><td>Atkinson samples are available in the comparator. They reproduce tone with scattered pixels.</td><td>Appropriate for a 1-bit shaded-art style; a poor default objective for minimal filled inventory icons.</td></tr>
<tr><td>Silhouette with bounded interior cuts</td><td>Protects thin handles and dark items; conservative cuts can leave generic blobs.</td><td>Best structural starting point, with explicit checks for lost identifying details.</td></tr>
<tr><td>Area cleanup / morphology</td><td>Filling singleton interior cuts makes strong-edge Stencil cleaner, but removes legitimate one-pixel marks too.</td><td>Prefer optional region filtering over a blanket 3×3 opening, which can erase 1px shafts and straps. <a href="https://scikit-image.org/docs/stable/api/skimage.morphology.html">Morphology documentation</a>.</td></tr>
<tr><td>Vector tracing</td><td>Researched, not benchmarked here.</td><td>Potrace traces an already chosen binary bitmap. It cannot recover item identity lost during binarization. Useful later for SVG output, not the missing semantic step. <a href="https://potrace.sourceforge.net/">Potrace</a>.</td></tr>
</tbody></table>
<p>Color2Gray was tested at α=10, θ=45° and 135°, and α=25, θ=45°, using all foreground pixel pairs in each cell. The complete-graph least-squares solution was calculated directly, its normal equations checked, its mean aligned to source Lab lightness, then clipped to [0,100] and encoded as 8-bit gray. That gray went through the actual Solid/Stencil code. This tests the published contrast-preservation objective with explicit alpha handling; it is not the authors’ reference implementation. RGB PCA was tested separately and is not labeled Color2Gray. Lu’s faster discrete RGB optimization was researched but not implemented.</p>
C2G_IMG
<p>My visual assessment: color contrast preservation is an optional source interpretation, not the central fix. The armor’s checker-like material texture becomes checker-like negative space. A filter cannot know whether those pixels indicate chainmail, a decorative pattern, a shadow or an important opening.</p></section>

<section><h2>Measured geometry, with its limits</h2>
<p>Each method uses all 65 cells. Retention is the mean fraction of original opaque pixels kept as ink. Added fragmentation compares eight-connected output components with the source’s component count. Singleton removed regions use four-connectivity within the source mask; they are not all enclosed holes. Metrics describe geometry, not item recognition. A solid blob scores very well on retention and connectivity and can still be useless.</p>
METRICS_TABLE
<p>Stencil Auto keeps 92.9% of the source on average. Its protected perimeter is working; its tendency to flatten dark armor and potion interiors is the corresponding cost. Strong edges reduce mean retention to 83.5%, and increase singleton removed regions from 141 to 309. Optional singleton cleanup removes those isolated cuts and raises retention to 88.0%, but also deletes meaningful tiny details. The percentile prototype is a counterexample to trusting tidiness metrics: it is clean and connected while remaining generic.</p>
<p>Whole-sheet Solid Auto and separate-cell Solid Auto differ by 200 pixels on general items, 227 on weapons, 134 on accessories and 292 on armor: <strong>853 pixels total</strong>. Whole-sheet and separate-cell Stencil outputs match on this dataset because its component segmentation successfully separates these items. This validates the recent per-sprite change, while showing why the same organization is needed for a threshold-based candidate. Connected components alone are not a reliable item detector when art touches, or one item contains detached parts.</p></section>

<section><h2>What the recent commits got right—and what to challenge</h2>
<p>I reviewed the recent None/Stencil sequence through b2711a4 and read palettes.md, styles.md, the design spec and the performance constraints. None is appropriately independent of palette/style. It changes the paint, not the pixel classification; selecting another output palette cannot recover missing features. For these 65 default Stencil outputs, I checked all 16,640 pixel positions: None produced only the requested ink or full transparency, and painted nothing outside the original alpha support.</p>
<ul><li><code>eb3ce96</code> / <code>60b7aef</code> / <code>d3d164d</code> add transparent painting, remembered None state and its initial controls.</li><li><code>820848f</code> introduces the structural fill-and-cut Stencil approach; <code>697dc07</code> exposes it in the UI.</li><li><code>09663d4</code> fixes correctness in frame statistics and transparent output handling.</li><li><code>6f95fbd</code> adds per-sprite Otsu and the median guard. Per-sprite analysis is supported by the experiments; interpreting “dark half” as “no line art” is not.</li><li><code>b2711a4</code> changes the None UI location; it has no bearing on conversion quality.</li></ul>
<p>Two descriptions in styles.md overstate the algorithm: “takes no notice of shading” is not true in a general sense, because its brightness histogram and RGB edges respond to shading; “a sprite ... is left whole” applies to brightness cuts, while edge cuts and Trim can still alter it. The current code is implementing its heuristic, but that heuristic is not a guarantee of minimal design.</p>
<p>The darkest single rim pixel is also a fragile reference for manual Cuts: one black outlier sets the level even when the meaningful drawn outline has several tones. Keep protects a geometric rim, not a detected stroke; Trim removes geometry, not just a black outline. A digital one-color icon also does not need the bridges required by a physical cut stencil, so preserving connectivity is a useful constraint, not a universal artistic law.</p></section>

<section><h2>The most defensible next implementation</h2>
<p><strong>Retain Stencil as a structural baseline. Replace the all-or-nothing brightness guard with region selection that degrades gradually.</strong> The following is a proposed algorithm, not a validated production winner:</p>
<ol><li>Determine the item boundary. Use known 16 × 16 cells when supplied; otherwise group nearby components conservatively. Keep the original alpha mask and record thin parts and original holes.</li><li>Make a few candidates per item: a tone fill, a conservative silhouette with dark cuts, and a silhouette with coherent chromatic seams. Use Luma and Value as cheap alternative interpretations; use mild edge-aware smoothing or palette clustering only when helpful.</li><li>Treat cut regions as candidates. Score contrast to their surroundings, persistence across nearby thresholds, area, thinness/elongation and continuity. Prefer coherent separators to broad lighting gradients and scattered texture. These remain heuristics and can reject real one-pixel marks.</li><li>Apply a bounded interior cut budget and topology checks to each candidate. Protect thin handles and source holes; avoid creating isolated ink or accidental breaks. If a cut is too destructive, skip or reduce that cut instead of restoring all cuts at once. Do not assume a fixed cut percentage works for every item.</li><li>Allow selective removal of a clearly darker drawn rim. Never globally erode every boundary pixel. This needs actual tests on narrow weapons and on the breastplate’s straps.</li><li>Select conservatively when evidence is strong. When viable candidates disagree, present two or three previews. A few candidates are likely to need less tuning than several interacting global sliders.</li></ol>
<p>For immediate experimentation in the current app, start with <strong>first color None, Stencil Auto, Outline Keep, Edges Off</strong>. Add edges only to recover missing details, and compare at native size. The breastplate’s threshold sweep does not reveal a single reliably convincing setting; it deserves a redraw or semantic interpretation if its identity must be unambiguous.</p>
<p>For new AI sources, ask for a readable straight-on silhouette, real transparent background, deliberate 1px gaps, no antialiasing, no dithering, no metallic lighting gradients, and a few flat semantic color roles. A small palette is helpful only if its roles and spatial clusters are consistent. If a one-color final icon is the actual target, generating or drawing that mask directly is a stronger starting point; inspect the real 16 × 16 result instead of trusting the prompt. These are design recommendations, not generation experiments performed in this study.</p>
<p><strong>Validation must test identity.</strong> Build labeled examples with acceptable one-color references. Run blinded native-size recognition and confusability checks—breastplate versus shield, sword versus wand, potion versus pouch—plus preference ratings for consistency. Hold out an additional AI item set before tuning the selection rules. Geometry measurements can guard against destruction, but cannot certify recognizable minimal icons. This sample establishes failure modes, not a globally optimal algorithm.</p></section>

<section><h2>All item comparisons and reproducibility</h2><p>The complete contact sheets keep every cell in source row order. The interactive comparator includes the grayscale/palette variants, current styles, experimental sources, cleanup prototypes and breastplate sweeps.</p>
GENERAL_IMG WEAPONS_IMG ACCESSORIES_IMG ARMOR_IMG
<p>Run <code>prepare.py</code>, <code>node current.mjs</code>, <code>compare.py</code>, <code>node verify.mjs</code>, then <code>report.py</code> from this folder. Python requires Pillow and NumPy; Node imports ../../src/lib/bitify.js. Copied original PNGs are included, so reproduction does not depend on clipboard files remaining in Temp. source-audit.json records original file hashes. ablation.json, metrics.json, summary.json and sheet-differences.json contain the numerical results.</p>
<p>Experimental parameters: bilateral radius 1 / spatial σ1 / RGB σ35; local mean window 5 with offset 8; Sauvola window 5, k=.2, R128; percentile cuts at the 20th percentile of eight-neighbor interior luma followed by removal of singleton cuts. Filtering windows exclude transparent pixels. No scaling or dithering precedes conversion. A grayscale quantization step adds its own rounding. Singleton cleanup is intentionally simple and can damage details; it is not an approved default.</p>
<p>Baseline validation: <strong>all 167 existing tests in 7 suites passed</strong>. The initial test run encountered a sandbox Temp rename error; rerunning with a workspace-local temporary directory passed. Research verification also checked None alpha/ink invariants and Color2Gray’s linear equations. The generated contact sheets were visually inspected. <code>node verify-report.mjs</code> checks the report script against a DOM stub across all item/variant/method combinations, sweep positions and backgrounds; this is not browser visual QA, which was unavailable through the agent’s browser surface. Sources are still PNGs; animation stability, phone performance, arbitrary sheet layouts and new AI generations have not been tested.</p></section>
'''
replacements={
 'BREAST_BASE':picture('breastplate-baselines.png','Current behavior on the original breastplate. White is the sole ink; checkerboard is transparent.'),
 'BREAST_ALT':picture('breastplate-alternatives.png','Experimental alternatives: none provides a clear automatic breastplate repair.'),
 'PALETTE_IMG':picture('palette-ablation.png','Stencil Auto after grayscale and foreground palette reduction. Changed geometry is not necessarily better geometry.'),
 'C2G_IMG':picture('color2gray-comparison.png','Color2Gray contrast preservation followed by the production Solid/Stencil algorithms.'),
 'GENERAL_IMG':picture('general-comparison.png','All 16 general inventory items.'),
 'WEAPONS_IMG':picture('weapons-comparison.png','All 16 weapon/tool cells; inspect thin shafts and handles.'),
 'ACCESSORIES_IMG':picture('accessories-comparison.png','All 16 accessory/container cells.'),
 'ARMOR_IMG':picture('armor-comparison.png','All 16 armor cells; texture and shade do not consistently correspond to meaningful cuts.'),
 'AUDIT_TABLE':f'<table><thead><tr><th>Source</th><th>Dimensions</th><th>Foreground colors</th><th>Opaque pixels</th><th>Alpha</th></tr></thead><tbody>{audit_rows}</tbody></table>',
 'ABL_TABLE':f'<details><summary>Exact grayscale and per-item palette ablation counts</summary><table><thead><tr><th>Method</th><th>Preparation</th><th>Changed items</th><th>Changed pixels</th></tr></thead><tbody>{abl_rows}</tbody></table></details>',
 'METRICS_TABLE':f'<div class="table-wrap"><table><thead><tr><th>Method</th><th>Mean retention</th><th>Empty</th><th>Added fragmentation</th><th>1px ink regions</th><th>1px removed regions</th></tr></thead><tbody>{metrics_rows}</tbody></table></div>',
 'ORIGINAL_MS':f'{verify["original"]["median_ms_per_65_items"]:.2f}',
 'GRAY_MS':f'{verify["gray"]["median_ms_per_65_items"]:.2f}',
}
for key,val in replacements.items(): body=body.replace(key,val)

style='''
*{box-sizing:border-box}body{margin:0;background:#13161b;color:#e7ecf4;font:16px/1.65 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:42px 32px 100px}header{max-width:960px}h1{font-size:clamp(32px,4vw,56px);line-height:1.1;margin:16px 0 24px}h2{font-size:26px;line-height:1.25;margin:0 0 20px}p{max-width:1000px}.eyebrow{font-size:13px;color:#93b7c9}.lead{font-size:21px;color:#c8dae6}section{padding:32px 0;border-top:1px solid #343c49;margin-top:30px}a{color:#91c9e8}code{background:#272e38;padding:2px 5px;border-radius:4px;font-size:13px}table{border-collapse:collapse;width:100%;font-size:14px;margin:22px 0}th,td{text-align:left;vertical-align:top;padding:12px;border-bottom:1px solid #343c49}th{color:#9cd2e8;background:#1d232b}td:first-child{font-weight:600}figure{margin:24px 0;padding:14px;background:#1a1e25;border:1px solid #343c49;border-radius:10px}figure img{display:block;max-width:100%;height:auto;margin:auto}figcaption{color:#a7b7c9;font-size:13px;padding:12px 2px 0}.controls{display:flex;flex-wrap:wrap;gap:12px;background:#1d232b;padding:18px;border-radius:10px}label{font-size:13px;color:#c2d3e3;display:flex;flex-direction:column;gap:6px}select{max-width:255px;background:#13161b;color:#e7ecf4;border:1px solid #536077;border-radius:6px;padding:9px;font-size:13px}#samples,#sweepSamples{display:flex;flex-wrap:wrap;gap:24px;margin:20px 0}.sample{padding:16px;border:1px solid #343c49;border-radius:8px;min-width:224px;max-width:270px}.sample h3{font-size:14px;height:42px;margin:0 0 12px}.sample canvas{image-rendering:pixelated;display:block}.native{padding:14px 0;display:flex;align-items:center;gap:14px;color:#aab6c8;font-size:12px}.zoom{width:192px;height:192px}details{background:#1b2028;border:1px solid #343c49;border-radius:8px;padding:18px;margin:22px 0}summary{cursor:pointer;font-weight:600}.table-wrap{overflow:auto}li{max-width:1000px;margin:12px 0}#sampleStats{font-size:13px;color:#adc4d2}@media(max-width:600px){main{padding:24px 16px 60px}section{padding-top:24px}th,td{padding:7px}.sample{min-width:0;width:100%}select{max-width:100%}.controls label{width:100%}table{font-size:12px}}
'''
script='''
const data=JSON.parse(document.getElementById('researchData').textContent);
const names=JSON.parse(document.getElementById('methodNames').textContent);
const $=id=>document.getElementById(id);
const item=$('item'),variant=$('variant'),methodA=$('methodA'),methodB=$('methodB'),bg=$('background');
const key=(id,v,m)=>`${id}/${v}/${m}`;
const masks=new Map(data.masks.map(x=>[key(x.id,x.variant,x.method),x.ink]));
for(const id of Object.keys(data.sources))item.add(new Option(id,id));
function refreshVariants(){const old=variant.value;variant.innerHTML='';for(const v of [...new Set(data.masks.filter(x=>x.id===item.value&&!x.method.startsWith('sweep')).map(x=>x.variant))])variant.add(new Option(v,v));variant.value=[...variant.options].some(o=>o.value===old)?old:'original';refreshMethods()}
function refreshMethods(){const list=[...new Set(data.masks.filter(x=>x.id===item.value&&x.variant===variant.value&&!x.method.startsWith('sweep')).map(x=>x.method))];for(const [sel,def] of [[methodA,'stencil_auto'],[methodB,'edges_clean']]){const prev=sel.value;sel.innerHTML='';for(const m of list)sel.add(new Option(names[m]||m,m));sel.value=list.includes(prev)?prev:list.includes(def)?def:list[0]}render()}
function pixels(canvas,source,isMask){canvas.width=16;canvas.height=16;const ctx=canvas.getContext('2d');const img=ctx.createImageData(16,16);for(let p=0;p<256;p++){const x=p%16,y=Math.floor(p/16);const light=bg.value==='light';let c=light?[244,246,248]:bg.value==='dark'?[20,23,29]:((Math.floor(x/2)+Math.floor(y/2))%2?[39,43,51]:[30,33,39]);if(isMask){if(source[p]==='1')c=light?[28,32,38]:[240,246,240]}else if(source[p*4+3]>=128)c=source.slice(p*4,p*4+3);img.data.set([...c,255],p*4)}ctx.putImageData(img,0,0)}
function sample(parent,title,source,isMask){const card=document.createElement('div');card.className='sample';const h=document.createElement('h3');h.textContent=title;card.append(h);const zoom=document.createElement('canvas');zoom.className='zoom';pixels(zoom,source,isMask);card.append(zoom);const native=document.createElement('div');native.className='native';const small=document.createElement('canvas');small.style.width='16px';small.style.height='16px';pixels(small,source,isMask);native.append(small,document.createTextNode('Native 16 × 16'));card.append(native);parent.append(card)}
function render(){const parent=$('samples');parent.innerHTML='';sample(parent,'Original colored source',data.sources[item.value],false);const a=masks.get(key(item.value,variant.value,methodA.value)),b=masks.get(key(item.value,variant.value,methodB.value));sample(parent,names[methodA.value]||methodA.value,a,true);sample(parent,names[methodB.value]||methodB.value,b,true);const ink=s=>[...s].filter(v=>v==='1').length;const differences=[...a].filter((v,i)=>v!==b[i]).length;$('sampleStats').textContent=`Candidate A: ${ink(a)} ink pixels · B: ${ink(b)} ink pixels · ${differences} pixels differ. The source panel always shows the original artwork; input preparation applies to the two candidates.`;renderSweep()}
function renderSweep(){const p=$('sweepSamples');p.innerHTML='';const t=$('sweep').value;$('sweepValue').textContent=t;for(const style of ['solid','stencil'])sample(p,`${style==='solid'?'Solid threshold':'Stencil Cuts'} ${t}`,masks.get(key('breastplate-1-1','original',`sweep_${style}_${t}`)),true)}
item.addEventListener('change',refreshVariants);variant.addEventListener('change',refreshMethods);methodA.addEventListener('change',render);methodB.addEventListener('change',render);bg.addEventListener('change',render);$('sweep').addEventListener('input',renderSweep);refreshVariants();
'''
doc=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bitify — one-color inventory icon research</title><style>{style}</style><main>{body}</main><script type="application/json" id="researchData">{json.dumps(data,separators=(",",":"))}</script><script type="application/json" id="methodNames">{json.dumps(names)}</script><script>{script}</script></html>'
(ROOT/'report.html').write_text(doc,encoding='utf-8')
assert not any(key in doc for key in replacements if key.endswith('_IMG') or key.endswith('_TABLE'))
print(f'Wrote self-contained report.html ({len(doc):,} characters).')
